apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: mysql
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: expense
    spec:
      containers:
      - name: mysql
        image: geethaprudhvi/mysql:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  type: ClusterIP
  selector: #labels are used as selectors
    app: mysql
    tier: mysql
    project: expense
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306 #pod port